### ISSUE TITLE
пять -> п'ять

### ISSUE THREAD

**Issue by egorsmkv** [lociko/ukraine_itn_wfst#3]
I propose to use `'` 

It's convenient to remove it or to replace by another character

**Comment by egorsmkv** [comment]
@lociko hi, what do you think about the subject?

**Comment by wincentbalin** [comment]
There are at least two different solutions:

1. Insert apostrophes into the `.tsv` files (as well into the alphabet)
2. Add a small FST that rewrites пять -> п'ять after every FST created by loading the `.tsv` files

**Comment by lociko** [comment]
Started working on this issue...

**Comment by egorsmkv** [comment]
Awesome, thank you!

**Comment by wincentbalin** [comment]
List of files with "пят":

./README.md
./tests/test_cardinal.py
./tests/test_decimal.py
./tests/test_measure.py
./tests/test_money.py
./ukr/data/numbers/cardinal/accusative/cardinals_digit.tsv
./ukr/data/numbers/cardinal/accusative/cardinals_hundred.tsv
./ukr/data/numbers/cardinal/accusative/cardinals_teen.tsv
./ukr/data/numbers/cardinal/accusative/cardinals_ties.tsv
./ukr/data/numbers/cardinal/dative/cardinals_digit.tsv
./ukr/data/numbers/cardinal/dative/cardinals_hundred.tsv
./ukr/data/numbers/cardinal/dative/cardinals_teen.tsv
./ukr/data/numbers/cardinal/dative/cardinals_ties.tsv
./ukr/data/numbers/cardinal/genitive/cardinals_digit.tsv
./ukr/data/numbers/cardinal/genitive/cardinals_hundred.tsv
./ukr/data/numbers/cardinal/genitive/cardinals_teen.tsv
./ukr/data/numbers/cardinal/genitive/cardinals_ties.tsv
./ukr/data/numbers/cardinal/instrumental/cardinals_digit.tsv
./ukr/data/numbers/cardinal/instrumental/cardinals_hundred.tsv
./ukr/data/numbers/cardinal/instrumental/cardinals_teen.tsv
./ukr/data/numbers/cardinal/instrumental/cardinals_ties.tsv
./ukr/data/numbers/cardinal/nominative/cardinals_digit.tsv
./ukr/data/numbers/cardinal/nominative/cardinals_hundred.tsv
./ukr/data/numbers/cardinal/nominative/cardinals_teen.tsv
./ukr/data/numbers/cardinal/nominative/cardinals_ties.tsv
./ukr/data/numbers/cardinal/prepositional/cardinals_digit.tsv
./ukr/data/numbers/cardinal/prepositional/cardinals_hundred.tsv
./ukr/data/numbers/cardinal/prepositional/cardinals_teen.tsv
./ukr/data/numbers/cardinal/prepositional/cardinals_ties.tsv
./ukr/data/numbers/ordinal/ordinal_digit.tsv
./ukr/data/numbers/ordinal/ordinal_hundred.tsv
./ukr/data/numbers/ordinal/ordinal_teen.tsv
./ukr/data/numbers/ordinal/ordinal_ties.tsv

**Comment by egorsmkv** [comment]
Also, there's the same issue with **девять -> дев'ять**

**Comment by wincentbalin** [comment]
At least we will not have any character set issues, as it is defined in `ukr\graph_utils.py` as
```python
NEMO_CHAR = utf8.VALID_UTF8_CHAR
```
