### ISSUE TITLE
PyPI package has a problem

### ISSUE THREAD

**Issue by egorsmkv** [lociko/ukraine_itn_wfst#5]
<img width="975" alt="image" src="https://user-images.githubusercontent.com/7875085/214949179-9ed71b74-5873-43dc-965e-512a11cd1275.png">

+

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/7875085/214949231-17877634-4bd6-499c-8863-847a3b2cb77c.png">

**Comment by egorsmkv** [comment]
This is ukr-itn 0.1.3

**Comment by lociko** [comment]
Fixed in latest version 0.1.5
Thansk for poiting it out!
